name: CI Stats Generation
on:
  workflow_dispatch: {}

jobs:
  ci-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            let commits = await github.rest.repos.listCommits({
              owner: 'apache',
              repo: 'helix',
            })
            
            let filteredCommits = commits.data.slice(0,3).map(c => c.sha)

            job_check_runs = []
            for (commit of filteredCommits) {
              console.log(commit)
              let commitCheckRuns = await github.rest.checks.listForRef({
                owner: 'apache',
                repo: 'helix',
                ref: commit
              })
              let first_check_run_url = commitCheckRuns.data.check_runs.slice(-1)[0].html_url
              let first_run = first_check_run_url.replace("https://github.com/apache/helix/actions/runs/", "").replace(/\/job.*/, "")
              
              let first_run_response = await fetch("https://github.com/apache/helix/actions/runs/" + first_run)
              let first_run_response_str = await first_run_response.text()
              
              for (let i = 0; i < first_run_response_str.match(/job_\d+/g).length; i++) {
                job_check_runs.push(first_run_response_str.match(/job_\d+/g)[i])
              }
            }
            console.log(job_check_runs)

