name: CI Stats Generation
on:
  workflow_dispatch: {}

jobs:
  ci-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            let commits = await github.rest.repos.listCommits({
              owner: 'apache',
              repo: 'helix',
            })
            
            let filteredCommits = commits.data.slice(0,3).map(c => c.sha)

            lastJobRuns = []
            for (commit of filteredCommits) {
              console.log(commit)
              let commitCheckRuns = await github.rest.checks.listForRef({
                owner: 'apache',
                repo: 'helix',
                ref: commit
              })
              let check_run_str = commitCheckRuns.data.check_runs.slice(-1)
              console.log(check_run_str)
              check_run_url = JSON.parse(check_run_str).html_url
              console.log(check_run_url)
              lastJobRuns.push(+url.replace("https://github.com/apache/helix/actions/runs/", "").replace(/\/job.*/, ""))
            }
            console.log(lastJobRuns)

