name: CI Stats Generation
on:
  workflow_dispatch: {}

jobs:
  ci-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            let commits = await github.rest.repos.listCommits({
              owner: 'apache',
              repo: 'helix',
            })
            
            let filteredCommits = commits.data.slice(0,3).map(c => c.sha)

            lastJobRuns = []
            for (commit of filteredCommits) {
              console.log(commit)
              let commitCheckRuns = await github.rest.checks.listForRef({
                owner: 'apache',
                repo: 'helix',
                ref: commit
              })
              console.log(commitCheckRuns.data.check_runs)
            }

